import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  complianceGuideSidebar: [{type: 'autogenerated', dirName: 'compliance-guide'}],
  guidanceSidebar: [{type: 'autogenerated', dirName: 'guidance'}],
  useCasesSidebar: [{type: 'autogenerated', dirName: 'use-cases'}],
  evidenceSidebar: [{type: 'autogenerated', dirName: 'evidence-assurance'}],
  standardsSidebar: [{type: 'autogenerated', dirName: 'standards-technologies'}],
  resourcesSidebar: [{type: 'autogenerated', dirName: 'resources'}],
};

export default sidebars;
