import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  standardsThreatsSidebar: [
    'standards-threats/index',
    {
      type: 'category',
      label: 'Standards and Regulations',
      link: {type: 'doc', id: 'standards-threats/standards-regulatory-drivers/index'},
      items: [
        'standards-threats/standards-regulatory-drivers/eu-cyber-resilience-act',
        'standards-threats/standards-regulatory-drivers/nis2',
      ],
    },
    'standards-threats/attack-failure-modes',
  ],
  practicesControlsSidebar: [
    'practices-controls/index',
    'practices-controls/best-practices',
    'practices-controls/lifecycle-map',
    'practices-controls/decision-guides',
    'practices-controls/procurement-supplier-assurance',
    'practices-controls/product-acceptance',
    'practices-controls/audit-compliance',
    'practices-controls/lifecycle-monitoring',
    'practices-controls/implementation-planning',
  ],
  evidenceSidebar: [{type: 'autogenerated', dirName: 'evidence'}],
  technologyOptionsSidebar: [{type: 'autogenerated', dirName: 'technology-options'}],
  resourcesSidebar: [
    'resources/index',
    'resources/glossary',
    'resources/supplier-questions',
    'resources/evidence-checklist',
    'resources/further-reading',
    'resources/artifact-map',
    'resources/standards-mapping-workflow',
    'resources/templates',
  ],
};

export default sidebars;
